spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: appuser
    password: apppass

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway管理なのでupdateは使わない
