spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false